"""Runtime configuration, read once from the environment.

Kept dependency-free (no pydantic-settings) on purpose — the surface is tiny and
`CONVENTIONS.md` favours fewer dependencies. Secrets are read from the environment
only; they never appear in the repo, database, or logs.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from decimal import Decimal, InvalidOperation
from functools import lru_cache
from pathlib import Path
from urllib.parse import urlsplit

from app.version import release_id

# Repository root (…/recipecollater). Used to locate migrations, templates, static, seed.
PACKAGE_DIR = Path(__file__).resolve().parent
REPO_ROOT = PACKAGE_DIR.parent


def _env_bool(name: str, default: bool) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def _env_usd_micros(name: str, default: str) -> int:
    """Read a dollar amount (e.g. "1.50") as integer micro-USD - money stays integer, not float."""
    raw = os.environ.get(name, default).strip() or default
    try:
        return int((Decimal(raw) * 1_000_000).to_integral_value())
    except (InvalidOperation, ValueError):
        return int((Decimal(default) * 1_000_000).to_integral_value())


@dataclass(frozen=True, slots=True)
class Settings:
    """Immutable process configuration."""

    # Single source of truth for links, Shortcut templates, callbacks (CONVENTIONS §11).
    app_base_url: str
    # Directory holding the SQLite databases, images, artifacts, and backups.
    data_dir: Path
    # Whether the app is served over HTTPS (mkcert/Tailscale upgrade). Controls the
    # `Secure` cookie flag. Default False = plain HTTP on the LAN.
    https_enabled: bool
    # Emit human-readable console logs instead of JSON (handy in a terminal / tests).
    log_console: bool
    # Exact staged release identifier (normally the Git commit SHA).
    release_id: str
    # Host-header allowlist. Prevents browser DNS-rebinding from reaching the LAN app.
    allowed_hosts: tuple[str, ...]
    # One-time first-run secret generated by deploy/install.sh. Not used after bootstrap.
    setup_token: str | None
    # AI extraction (Phase 2). No key -> the LLM fallback is disabled; schema.org still works.
    anthropic_api_key: str | None
    ai_model: str
    # Spend caps in integer micro-USD (money stays integer, per CONVENTIONS 1).
    ai_daily_cap_micros: int
    ai_monthly_cap_micros: int

    @property
    def ai_enabled(self) -> bool:
        return bool(self.anthropic_api_key)

    @property
    def db_path(self) -> Path:
        return self.data_dir / "recipecollater.db"

    @property
    def queue_db_path(self) -> Path:
        # The Huey queue is a *separate* SQLite file (CONVENTIONS §3).
        return self.data_dir / "queue.db"

    @property
    def images_dir(self) -> Path:
        return self.data_dir / "images"

    @property
    def artifacts_dir(self) -> Path:
        return self.data_dir / "artifacts"

    @property
    def backups_dir(self) -> Path:
        return self.data_dir / "backups"

    @property
    def worker_heartbeat_path(self) -> Path:
        return self.data_dir / "worker-heartbeat.json"

    @property
    def cookie_secure(self) -> bool:
        return self.https_enabled

    def ensure_dirs(self) -> None:
        for path in (
            self.data_dir,
            self.images_dir,
            self.artifacts_dir,
            self.backups_dir,
        ):
            path.mkdir(parents=True, exist_ok=True)


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    data_dir = Path(os.environ.get("RC_DATA_DIR", str(REPO_ROOT / "data"))).resolve()
    app_base_url = os.environ.get("APP_BASE_URL", "http://recipes.local").rstrip("/")
    base_host = urlsplit(app_base_url).hostname or "recipes.local"
    configured_hosts = os.environ.get("RC_ALLOWED_HOSTS", "")
    allowed_hosts = tuple(
        dict.fromkeys(
            host.strip()
            for host in (
                configured_hosts.split(",")
                if configured_hosts
                else [base_host, "localhost", "127.0.0.1"]
            )
            if host.strip()
        )
    )
    return Settings(
        app_base_url=app_base_url,
        data_dir=data_dir,
        https_enabled=_env_bool("RC_HTTPS", False),
        log_console=_env_bool("RC_LOG_CONSOLE", False),
        release_id=release_id(REPO_ROOT),
        allowed_hosts=allowed_hosts,
        setup_token=os.environ.get("RC_SETUP_TOKEN", "").strip() or None,
        anthropic_api_key=os.environ.get("RC_ANTHROPIC_API_KEY", "").strip() or None,
        ai_model=os.environ.get("RC_AI_MODEL", "claude-sonnet-5").strip() or "claude-sonnet-5",
        ai_daily_cap_micros=_env_usd_micros("RC_AI_DAILY_CAP_USD", "1.00"),
        ai_monthly_cap_micros=_env_usd_micros("RC_AI_MONTHLY_CAP_USD", "10.00"),
    )


def reset_settings_cache() -> None:
    """Clear the cached settings (tests set env vars then rebuild)."""
    get_settings.cache_clear()
